// import { dirname } from "path";
// import { fileURLToPath } from "url";
// import { FlatCompat } from "@eslint/eslintrc";

// const __filename = fileURLToPath(import.meta.url);
// const __dirname = dirname(__filename);

// const compat = new FlatCompat({
//   baseDirectory: __dirname,
// });

// const eslintConfig = [
//   ...compat.extends("next/core-web-vitals", "next/typescript"),
// ];

// export default eslintConfig;

// import { dirname } from 'path';
// import { fileURLToPath } from 'url';
// import { FlatCompat } from '@eslint/eslintrc';

// const __filename = fileURLToPath(import.meta.url);
// const __dirname = dirname(__filename);

// const compat = new FlatCompat({
//   baseDirectory: __dirname,
// });

// const eslintConfig = [
//   // Convert the old-style config to the new flat config
//   ...compat.extends(
//     'eslint:recommended',
//     'next',
//     'next/core-web-vitals',
//     'prettier'
//   ),

//   {
//     plugins: {
//       prettier: require('eslint-plugin-prettier'),
//     },
//     rules: {
//       'prettier/prettier': 'error',
//     },
//   },
// ];

// export default eslintConfig;

import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js'; // <-- Add this import
import prettierPlugin from 'eslint-plugin-prettier';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended, // <-- Add this option
});

const eslintConfig = [
  ...compat.extends(
    'eslint:recommended',
    'next',
    'next/core-web-vitals',
    'prettier'
  ),
  {
    ignores: [
      '**/node_modules/**',
      '.next/**',
      'dist/**',
      'build/**',
      '**/polyfills/**',
      '**/__generated__/**', // example: ignore other autogenerated folders
    ],
  },
  {
    plugins: {
      prettier: prettierPlugin,
    },
    rules: {
      'prettier/prettier': 'error',
      '@next/next/no-img-element': 'off', // <-- DISABLE the img warning here
    },
  },
];

export default eslintConfig;
