name: Build and Deploy to vercel

on:
  push:
    branches:
      - master # Replace with your main development branch

jobs:
  # build the project first and deploy it
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm install
      # building our project
      - name: Build
        run: npm run build

      - name: Deploy to prod url
        # main is the branch name where new code is pushed

        # check on the github market place to gett the heroku
      - uses: nexterias/actions-vercel@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}

          production: ${{ github.ref == 'refs/heads/master' }}
          prebuilt: true # If set to true, build will be performed using GitHub Actions.


          # build_dir: 'your-build-directory' # Change this to your build directory if different from the root
# commented section notes:
# it might through permission error during deployment,
# go the repo settings, Action > General > Workflow permissions
# and select Read and Write permissions
# click save,
# re-run jobs and it should fix the error

# uses: peaceiris/actions-gh-pages@v3
# with:
#   github_token: ${{ secrets.GITHUB_TOKEN }}
#   publish_dir: ./dist
# publish_branch: prod-gh-pages  // by default it will create gh-pages branch and push everything of dist folder inside it.

# - name: Deploy to dev url
#   if: github.ref == 'refs/heads/develop'
#   uses: peaceiris/actions-gh-pages@v3
#   with:
#     github_token: ${{ secrets.GITHUB_TOKEN }}
# publish_dir: ./dist
# publish_branch: dev-gh-pages
